name: model-training
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: iterative/setup-cml@v2
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./work
        run: |
          pip install -r requirements.txt
          echo "## MODEL METRICS" > report.md
          cat ./work/metrics.txt >> report.md

          echo 'My first CML report' > report.md
          echo '![](./work/feature_importance.png)' >> report.md
          echo '![](./work/residuals.png)' >> report.md
          cml comment create --publish report.md
