name: model-training
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.CML_TOKEN }}
        run: |
          pip install -r requirements.txt
          python train.py --output feature_importance.png
          echo "## MODEL METRICS" > report.md
          cat metrics.txt >> report.md

          echo "### Data viz" >> report.md
          echo "![](./feature_importance.png)" >> report.md
          echo "![](./residuals.png)" >> report.md
          cml comment create report.md
